##
## EPITECH PROJECT, 2021
## 302separation
## File description:
## Makefile
##

SRC     =       302separation.py

NAME = 			302separation

all:    		$(NAME)

$(NAME):
		cp $(SRC) $(NAME)
		chmod +x $(NAME)
clean:
		rm -f *~
fclean: clean
		rm -f $(NAME)
		rm -rf __pycache__

re:     fclean  all
